# 设置服务的host
host: "127.0.0.1"
# 设置服务的port
# port: 8000

# 程序环境变量设置 可在ENV 下自定义环境变量 通过 process[ENV].[自定义变量]
ENV: 
  modal: 'DEV'

# 热加载更新
hotUpdata: true
hotFiles: ['src']

# 设置静态资源 文件夹 默认值如下
staticResource: 
  fileName: ["www", "resourceFiles"]

# 文件上传临时文件夹
# file_tmp: upload_tmp
